<a href="https://colab.research.google.com/github/michelebazana/Instrucoes/blob/main/AlgoritmoSLGauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np

In [33]:
def sistemaTriangularSuperior(U,y):
  n, nc = np.shape(U)
  x = np.zeros((n,1))
  for i in range(n-1,-1,-1):
    x[i,0] = (y[i,0] - U[i,i:n]@x[i:n,0])/U[i,i]
  return x

In [34]:
A = np.array([[4,-2],[2,1]])
b = np.array([[8],[0]])

Aa = np.concatenate((A,b),1)

#coluna j = 0 (primeira coluna)
j = 0
pivo = A[j,j]

#linha i = 1 (segunda linha)
i = 1
fator = Aa[i,j] / pivo
Aa[i,0:] = Aa[i,0:] - fator*Aa[j,0:]

U = Aa[0:, 0:2]
y = Aa[0:,2:]
x = sistemaTriangularSuperior(U,y)

In [35]:
print(Aa)
print(U)
print(y)
print(x)

[[ 4 -2  8]
 [ 0  2 -4]]
[[ 4 -2]
 [ 0  2]]
[[ 8]
 [-4]]
[[ 1.]
 [-2.]]


In [36]:
print(A@x)
# A vezes x precisa ser igual a b

[[8.]
 [0.]]


In [39]:
def eliminacaoGaussSistematizada(A,b):
  n,_ = np.shape(A)
  Aa = np.concatenate((A,b),1)

  for j in range(n-1):
    pivo = A[j,j]
    for i in range(j+1,n):
      fator = Aa[i,j] / pivo
      Aa[i,0:] = Aa[i,0:] - fator*Aa[j,0:]

  U = Aa[0:, 0:n]
  y = Aa[0:,n:]
  x = sistemaTriangularSuperior(U,y)
  return x

In [43]:
x = eliminacaoGaussSistematizada(A,b)
print(x)

[[ 1.]
 [-2.]]
